#ifndef CLAW_JS_INCLUDE_CLAW_DEFINES_H
#define CLAW_JS_INCLUDE_CLAW_DEFINES_H

enum ClawDType {
	CLAW_INT8,
	CLAW_UINT8,
	CLAW_INT16,
	CLAW_UINT16,
	CLAW_INT32,
	CLAW_UINT32,
	CLAW_INT64,
	CLAW_UINT64,
	CLAW_FLT32,
	CLAW_FLT64,
};

typedef unsigned long long claw_dlen;

#endif //CLAW_JS_INCLUDE_CLAW_DEFINES_H
